/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'suhalemk' at '10/7/15 10:23 PM' with Gradle 2.4
 *
 * @author suhalemk, @date 10/7/15 10:23 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
